<%-- 
    Document   : SessionShowData
    Created on : 4 Dec, 2020, 2:39:14 PM
    Author     : Chaudhary
--%>

<%@page contentType="text/html" pageEncoding="UTF-8"%>
<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <title>Session Show Data Page</title>
    </head>
    <body>
         <form method="post">
        
            <table>
                <tr>
                    <td>
                        <h4>Full Name</h4>
                    </td>
                    <td>
                        <h4>
                        <%
                        if(session.getAttribute("Fname")!=null)
                        {
                            out.print(session.getAttribute("Fname").toString());
                        }
                        else
                        {
                            response.sendRedirect("MyQueryString.jsp");
                        }
                        %>
                        </h4>
                    </td>   
                </tr>
                <tr>
                    <td>
                        <h4>Email</h4>
                    </td>
                    <td>
                        <h4>
                        <%
                       if(session.getAttribute("Email")!=null)
                        {
                            out.print(session.getAttribute("Email").toString());
                        }
                        else
                        {
                            response.sendRedirect("MyQueryString.jsp");
                        }
                        %>
                        </h4>
                    </td>   
                </tr>
                <tr>
                    <td>
                        <h4>Password</h4>
                    </td>
                    <td>
                        <h4>
                        <%
                        if(session.getAttribute("Password")!=null)
                        {
                            out.print(session.getAttribute("Password").toString());
                        }
                        else
                        {
                            response.sendRedirect("MyQueryString.jsp");
                        }
                        %>
                        </h4>
                    </td>   
                </tr>
                <tr>
                    <td>
                        <h4>Gender</h4>
                    </td>
                    <td>
                        <h4>
                        <%
                        if(session.getAttribute("Gender")!=null)
                        {
                            out.print(session.getAttribute("Gender").toString());
                        }
                        else
                        {
                            response.sendRedirect("MyQueryString.jsp");
                        }
                        %>
                        </h4>
                    </td>   
                </tr>
                <tr>
                    <td>
                        <h4>Date Of Birth</h4>
                    </td>
                    <td>
                        <h4>
                        <%
                        if(session.getAttribute("Dob")!=null)
                        {
                            out.print(session.getAttribute("Dob").toString());
                        }
                        else
                        {
                            response.sendRedirect("MyQueryString.jsp");
                        }
                        %>
                        </h4>
                    </td>   
                </tr>
                <tr>
                    <td>
                        <h4>Address</h4>
                    </td>
                    <td>
                        <h4>
                        <%
                       if(session.getAttribute("Address")!=null)
                        {
                            out.print(session.getAttribute("Address").toString());
                        }
                        else
                        {
                            response.sendRedirect("MyQueryString.jsp");
                        }
                        %>
                        </h4>
                    </td>   
                </tr>
                <tr>
                    <td>
                        <h4>Country</h4>
                    </td>
                    <td>
                        <h4>
                        <%
                       if(session.getAttribute("Country")!=null)
                        {
                            out.print(session.getAttribute("Country").toString());
                        }
                        else
                        {
                            response.sendRedirect("MyQueryString.jsp");
                        }
                        %>
                        </h4>
                    </td>   
                </tr>
                <tr>
                    <td>
                        <h4>State</h4>
                    </td>
                    <td>
                        <h4>
                        <%
                       if(session.getAttribute("State")!=null)
                        {
                            out.print(session.getAttribute("State").toString());
                        }
                        else
                        {
                            response.sendRedirect("MyQueryString.jsp");
                        }
                        %>
                        </h4>
                    </td>   
                </tr>
                <tr>
                    <td>
                        <h4>Pincode</h4>
                    </td>
                    <td>
                        <h4>
                        <%
                        if(session.getAttribute("Pincode")!=null)
                        {
                            out.print(session.getAttribute("Pincode").toString());
                        }
                        else
                        {
                            response.sendRedirect("MyQueryString.jsp");
                        }
                        %>
                        </h4>
                    </td>   
                </tr>
                <tr>
                    <td>
                        <h4>Contact</h4>
                    </td>
                    <td>
                        <h4>
                        <%
                       if(session.getAttribute("Contact")!=null)
                        {
                            out.print(session.getAttribute("Contact").toString());
                        }
                        else
                        {
                            response.sendRedirect("MyQueryString.jsp");
                        }
                        %>
                        </h4>
                    </td>   
                </tr>
                <tr>
                    <td>
                        <h4>Security Quetions</h4>
                    </td>
                    <td>
                        <h4>
                        <%
                        if(session.getAttribute("SecurityQue")!=null)
                        {
                            out.print(session.getAttribute("SecurityQue").toString());
                        }
                        else
                        {
                            response.sendRedirect("MyQueryString.jsp");
                        }
                        %>
                        </h4>
                    </td>   
                </tr>
                <tr>
                    <td>
                        <h4>Security Answer</h4>
                    </td>
                    <td>
                        <h4>
                        <%
                       if(session.getAttribute("SecurityAns")!=null)
                        {
                            out.print(session.getAttribute("SecurityAns").toString());
                        }
                        else
                        {
                            response.sendRedirect("MyQueryString.jsp");
                        }
                        %>
                        </h4>
                    </td>   
                </tr>
                <tr>
                    <td>
                        <h4>Image</h4>
                    </td>
                    <td>
                        <h4>
                        <%
                       if(session.getAttribute("Image")!=null)
                        {
                            out.print(session.getAttribute("Image").toString());
                        }
                        else
                        {
                            response.sendRedirect("MyQueryString.jsp");
                        }
                        %>
                        </h4>
                    </td>   
                </tr>
                
            </table>
            
            
        </form>
       
        
    </body>
</html>
